### ISSUE TITLE
Active or deprecated?

### ISSUE THREAD

**Issue by ShalokShalom** [migueldeicaza/GodotSwift#9]
I maintain the list of Godot`s language support: https://github.com/Vivraan/godot-lang-support

Do you think, this implementation will ever see a continuation?

**Comment by migueldeicaza** [comment]
Hello!

No, this one is dead, I have now a new version using GDExtension that just booted, and will use that instead.

**Comment by ShalokShalom** [comment]
Thanks, I will include them in our list :)
